export default {
    FETCH_REQUEST : 'categories/FETCH_REQUEST',
    FETCH_SUCCESS : 'categories/FETCH_SUCCESS',
    FETCH_FAILURE : 'categories/FETCH_FAILURE',

    UPDATE_REQUEST : 'categories/UPDATE_REQUEST',
    UPDATE_SUCCESS : 'categories/UPDATE_SUCCESS',
    UPDATE_FAILURE : 'categories/UPDATE_FAILURE',

    REMOVE_ATTRIBUTE_REQUEST : 'categories/REMOVE_ATTRIBUTE_REQUEST',
    REMOVE_ATTRIBUTE_SUCCESS : 'categories/REMOVE_ATTRIBUTE_SUCCESS',
    REMOVE_ATTRIBUTE_FAILURE : 'categories/REMOVE_ATTRIBUTE_FAILURE'
};
